# Generated by Django 4.1.4 on 2022-12-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_profile_bio_profile_id_user_profile_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="id_user",
            field=models.IntegerField(default=None),
        ),
    ]
